services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: kahunas-image
    container_name: kahunas-container
    restart: unless-stopped



    environment:
      DB_CONNECTION: mysql
      DB_HOST: db  
      DB_PORT: 3306
      DB_DATABASE: kahunas_db
      DB_USERNAME: root 
      DB_PASSWORD: secret

    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - kahunas-network

  kahunasserver:
    image: nginx:alpine
    container_name: nginx_webserver
    restart: unless-stopped
    ports:
      - "8001:80"
    volumes:
      - .:/var/www
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - kahunas-network

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret   
      MYSQL_DATABASE: kahunas_db        
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql      
    networks:
      - kahunas-network

volumes:
  db_data: 
networks:
  kahunas-network:
    driver: bridge
